// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"github.com/speakeasy-sdks/go-sdk-full/pkg/utils"
	"net/http"
)

type CancelPaymentLinkRequest struct {
	LinkID        string  `pathParam:"style=simple,explode=false,name=link_id"`
	XAPIVersion   *string `default:"2022-09-01" header:"style=simple,explode=false,name=x-api-version"`
	XClientID     string  `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret string  `header:"style=simple,explode=false,name=x-client-secret"`
}

func (c CancelPaymentLinkRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelPaymentLinkRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CancelPaymentLinkRequest) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}

func (o *CancelPaymentLinkRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *CancelPaymentLinkRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *CancelPaymentLinkRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type CancelPaymentLinkResponse struct {
	ContentType string
	Headers     map[string][]string
	// Cannot cancel Payment Link if status is not ACTIVE
	LinkCancelledError *shared.LinkCancelledError
	// Payment Link cancelled
	LinkCancelledResponse *shared.LinkCancelledResponse
	StatusCode            int
	RawResponse           *http.Response
}

func (o *CancelPaymentLinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelPaymentLinkResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CancelPaymentLinkResponse) GetLinkCancelledError() *shared.LinkCancelledError {
	if o == nil {
		return nil
	}
	return o.LinkCancelledError
}

func (o *CancelPaymentLinkResponse) GetLinkCancelledResponse() *shared.LinkCancelledResponse {
	if o == nil {
		return nil
	}
	return o.LinkCancelledResponse
}

func (o *CancelPaymentLinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelPaymentLinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
