// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type CreateOfferRequest struct {
	CreateOfferBackendRequest *shared.CreateOfferBackendRequest `request:"mediaType=application/json"`
	XAPIVersion               *string                           `header:"style=simple,explode=false,name=x-api-version"`
	XClientID                 string                            `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret             string                            `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *CreateOfferRequest) GetCreateOfferBackendRequest() *shared.CreateOfferBackendRequest {
	if o == nil {
		return nil
	}
	return o.CreateOfferBackendRequest
}

func (o *CreateOfferRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *CreateOfferRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *CreateOfferRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type CreateOfferResponse struct {
	ContentType string
	Headers     map[string][]string
	// OK
	OfferEntity *shared.OfferEntity
	StatusCode  int
	RawResponse *http.Response
}

func (o *CreateOfferResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateOfferResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateOfferResponse) GetOfferEntity() *shared.OfferEntity {
	if o == nil {
		return nil
	}
	return o.OfferEntity
}

func (o *CreateOfferResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateOfferResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
