// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type CreaterefundRequest struct {
	CreateRefundRequest *shared.CreateRefundRequest `request:"mediaType=application/json"`
	OrderID             string                      `pathParam:"style=simple,explode=false,name=order_id"`
	XAPIVersion         *string                     `header:"style=simple,explode=false,name=x-api-version"`
	XClientID           string                      `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret       string                      `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *CreaterefundRequest) GetCreateRefundRequest() *shared.CreateRefundRequest {
	if o == nil {
		return nil
	}
	return o.CreateRefundRequest
}

func (o *CreaterefundRequest) GetOrderID() string {
	if o == nil {
		return ""
	}
	return o.OrderID
}

func (o *CreaterefundRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *CreaterefundRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *CreaterefundRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type CreaterefundResponse struct {
	ContentType string
	// Any bad or invalid request will lead to following error object
	ErrorResponse *shared.ErrorResponse
	Headers       map[string][]string
	// Refund created
	RefundsEntity *shared.RefundsEntity
	StatusCode    int
	RawResponse   *http.Response
}

func (o *CreaterefundResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreaterefundResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *CreaterefundResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreaterefundResponse) GetRefundsEntity() *shared.RefundsEntity {
	if o == nil {
		return nil
	}
	return o.RefundsEntity
}

func (o *CreaterefundResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreaterefundResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
