// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type CreateTerminalsRequest struct {
	CreateTerminalRequest *shared.CreateTerminalRequest `request:"mediaType=application/json"`
	XAPIVersion           *string                       `header:"style=simple,explode=false,name=x-api-version"`
	XClientID             string                        `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret         string                        `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *CreateTerminalsRequest) GetCreateTerminalRequest() *shared.CreateTerminalRequest {
	if o == nil {
		return nil
	}
	return o.CreateTerminalRequest
}

func (o *CreateTerminalsRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *CreateTerminalsRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *CreateTerminalsRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type CreateTerminalsResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// Terminal created
	TerminalResponse *shared.TerminalResponse
}

func (o *CreateTerminalsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateTerminalsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateTerminalsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateTerminalsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateTerminalsResponse) GetTerminalResponse() *shared.TerminalResponse {
	if o == nil {
		return nil
	}
	return o.TerminalResponse
}
