// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type EligibilityCardlessEMIRequest struct {
	EligibilityCardlessEMIRequest *shared.EligibilityCardlessEMIRequest `request:"mediaType=application/json"`
	XAPIVersion                   *string                               `header:"style=simple,explode=false,name=x-api-version"`
	XClientID                     string                                `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret                 string                                `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *EligibilityCardlessEMIRequest) GetEligibilityCardlessEMIRequest() *shared.EligibilityCardlessEMIRequest {
	if o == nil {
		return nil
	}
	return o.EligibilityCardlessEMIRequest
}

func (o *EligibilityCardlessEMIRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *EligibilityCardlessEMIRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *EligibilityCardlessEMIRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type EligibilityCardlessEMIResponse struct {
	ContentType string
	// OK
	EligibleCardlessEMIEntities []shared.EligibleCardlessEMIEntity
	Headers                     map[string][]string
	StatusCode                  int
	RawResponse                 *http.Response
}

func (o *EligibilityCardlessEMIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EligibilityCardlessEMIResponse) GetEligibleCardlessEMIEntities() []shared.EligibleCardlessEMIEntity {
	if o == nil {
		return nil
	}
	return o.EligibleCardlessEMIEntities
}

func (o *EligibilityCardlessEMIResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *EligibilityCardlessEMIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EligibilityCardlessEMIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
