// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type EligibilityOfferRequest struct {
	EligibilityOffersRequest *shared.EligibilityOffersRequest `request:"mediaType=application/json"`
	XAPIVersion              *string                          `header:"style=simple,explode=false,name=x-api-version"`
	XClientID                string                           `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret            string                           `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *EligibilityOfferRequest) GetEligibilityOffersRequest() *shared.EligibilityOffersRequest {
	if o == nil {
		return nil
	}
	return o.EligibilityOffersRequest
}

func (o *EligibilityOfferRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *EligibilityOfferRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *EligibilityOfferRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type EligibilityOfferResponse struct {
	ContentType string
	// OK
	EligibleOffersEntities []shared.EligibleOffersEntity
	Headers                map[string][]string
	StatusCode             int
	RawResponse            *http.Response
}

func (o *EligibilityOfferResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EligibilityOfferResponse) GetEligibleOffersEntities() []shared.EligibleOffersEntity {
	if o == nil {
		return nil
	}
	return o.EligibleOffersEntities
}

func (o *EligibilityOfferResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *EligibilityOfferResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EligibilityOfferResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
