// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"github.com/speakeasy-sdks/go-sdk-full/pkg/utils"
	"net/http"
)

type FetchAllSavedInstrumentsRequest struct {
	CustomerID     string  `pathParam:"style=simple,explode=false,name=customer_id"`
	instrumentType string  `const:"card" queryParam:"style=form,explode=true,name=instrument_type"`
	XAPIVersion    *string `default:"2022-09-01" header:"style=simple,explode=false,name=x-api-version"`
	XClientID      string  `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret  string  `header:"style=simple,explode=false,name=x-client-secret"`
}

func (f FetchAllSavedInstrumentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FetchAllSavedInstrumentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *FetchAllSavedInstrumentsRequest) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *FetchAllSavedInstrumentsRequest) GetInstrumentType() string {
	return "card"
}

func (o *FetchAllSavedInstrumentsRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *FetchAllSavedInstrumentsRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *FetchAllSavedInstrumentsRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type FetchAllSavedInstrumentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Any bad or invalid request will lead to following error object
	ErrorResponse *shared.ErrorResponse
	// OK
	FetchAllSavedInstruments []shared.FetchAllSavedInstruments
	Headers                  map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *FetchAllSavedInstrumentsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *FetchAllSavedInstrumentsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *FetchAllSavedInstrumentsResponse) GetFetchAllSavedInstruments() []shared.FetchAllSavedInstruments {
	if o == nil {
		return nil
	}
	return o.FetchAllSavedInstruments
}

func (o *FetchAllSavedInstrumentsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *FetchAllSavedInstrumentsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *FetchAllSavedInstrumentsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
