// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type GetPaymentLinkOrdersRequest struct {
	LinkID        string  `pathParam:"style=simple,explode=false,name=link_id"`
	XAPIVersion   *string `header:"style=simple,explode=false,name=x-api-version"`
	XClientID     string  `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret string  `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *GetPaymentLinkOrdersRequest) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}

func (o *GetPaymentLinkOrdersRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *GetPaymentLinkOrdersRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *GetPaymentLinkOrdersRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type GetPaymentLinkOrdersResponse struct {
	ContentType string
	Headers     map[string][]string
	// OK
	LinkOrdersResponses []shared.LinkOrdersResponse
	StatusCode          int
	RawResponse         *http.Response
}

func (o *GetPaymentLinkOrdersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPaymentLinkOrdersResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetPaymentLinkOrdersResponse) GetLinkOrdersResponses() []shared.LinkOrdersResponse {
	if o == nil {
		return nil
	}
	return o.LinkOrdersResponses
}

func (o *GetPaymentLinkOrdersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPaymentLinkOrdersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
