// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"github.com/speakeasy-sdks/go-sdk-full/pkg/utils"
	"net/http"
)

type OTPRequestRequest struct {
	OTPRequest  *shared.OTPRequest `request:"mediaType=application/json"`
	PaymentID   string             `pathParam:"style=simple,explode=false,name=payment_id"`
	XAPIVersion *string            `default:"2022-09-01" header:"style=simple,explode=false,name=x-api-version"`
}

func (o OTPRequestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OTPRequestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OTPRequestRequest) GetOTPRequest() *shared.OTPRequest {
	if o == nil {
		return nil
	}
	return o.OTPRequest
}

func (o *OTPRequestRequest) GetPaymentID() string {
	if o == nil {
		return ""
	}
	return o.PaymentID
}

func (o *OTPRequestRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

type OTPRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Any bad or invalid request will lead to following error object
	ErrorResponse *shared.ErrorResponse
	Headers       map[string][]string
	// OK
	OTPResponseEntity *shared.OTPResponseEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *OTPRequestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OTPRequestResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OTPRequestResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *OTPRequestResponse) GetOTPResponseEntity() *shared.OTPResponseEntity {
	if o == nil {
		return nil
	}
	return o.OTPResponseEntity
}

func (o *OTPRequestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OTPRequestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
