// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/models/shared"
	"net/http"
)

type PostSettlementsRequest struct {
	FetchSettlementReconRequest *shared.FetchSettlementReconRequest `request:"mediaType=application/json"`
	XAPIVersion                 *string                             `header:"style=simple,explode=false,name=x-api-version"`
	XClientID                   string                              `header:"style=simple,explode=false,name=x-client-id"`
	XClientSecret               string                              `header:"style=simple,explode=false,name=x-client-secret"`
}

func (o *PostSettlementsRequest) GetFetchSettlementReconRequest() *shared.FetchSettlementReconRequest {
	if o == nil {
		return nil
	}
	return o.FetchSettlementReconRequest
}

func (o *PostSettlementsRequest) GetXAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.XAPIVersion
}

func (o *PostSettlementsRequest) GetXClientID() string {
	if o == nil {
		return ""
	}
	return o.XClientID
}

func (o *PostSettlementsRequest) GetXClientSecret() string {
	if o == nil {
		return ""
	}
	return o.XClientSecret
}

type PostSettlementsResponse struct {
	ContentType string
	// Any bad or invalid request will lead to following error object
	ErrorResponse *shared.ErrorResponse
	// OK
	FetchSettlement *shared.FetchSettlement
	Headers         map[string][]string
	StatusCode      int
	RawResponse     *http.Response
}

func (o *PostSettlementsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSettlementsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *PostSettlementsResponse) GetFetchSettlement() *shared.FetchSettlement {
	if o == nil {
		return nil
	}
	return o.FetchSettlement
}

func (o *PostSettlementsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostSettlementsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSettlementsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
