// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type LinkCancelledError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

var _ error = &LinkCancelledError{}

func (e *LinkCancelledError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
