// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AppProvider - Specify the provider through which the payment must be processed.
type AppProvider string

const (
	AppProviderGpay       AppProvider = "gpay"
	AppProviderPhonepe    AppProvider = "phonepe"
	AppProviderOla        AppProvider = "ola"
	AppProviderPaytm      AppProvider = "paytm"
	AppProviderAmazon     AppProvider = "amazon"
	AppProviderAirtel     AppProvider = "airtel"
	AppProviderFreecharge AppProvider = "freecharge"
	AppProviderMobikwik   AppProvider = "mobikwik"
	AppProviderJio        AppProvider = "jio"
)

func (e AppProvider) ToPointer() *AppProvider {
	return &e
}

func (e *AppProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "gpay":
		fallthrough
	case "phonepe":
		fallthrough
	case "ola":
		fallthrough
	case "paytm":
		fallthrough
	case "amazon":
		fallthrough
	case "airtel":
		fallthrough
	case "freecharge":
		fallthrough
	case "mobikwik":
		fallthrough
	case "jio":
		*e = AppProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppProvider: %v", v)
	}
}

type App struct {
	// Specify the channel through which the payment must be processed.
	Channel string `json:"channel"`
	// Customer phone number associated with a wallet for payment.
	Phone string `json:"phone"`
	// Specify the provider through which the payment must be processed.
	Provider AppProvider `json:"provider"`
}

func (o *App) GetChannel() string {
	if o == nil {
		return ""
	}
	return o.Channel
}

func (o *App) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}

func (o *App) GetProvider() AppProvider {
	if o == nil {
		return AppProvider("")
	}
	return o.Provider
}
