// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AppPaymentMethod struct {
	App App `json:"app"`
}

func (o *AppPaymentMethod) GetApp() App {
	if o == nil {
		return App{}
	}
	return o.App
}
