// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/types"
	"github.com/speakeasy-sdks/go-sdk-full/pkg/utils"
)

type AuthenticationError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// authentication_error
	type_ *string `const:"authentication_error" json:"type,omitempty"`
}

func (a AuthenticationError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AuthenticationError) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *AuthenticationError) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AuthenticationError) GetType() *string {
	return types.String("authentication_error")
}
