// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CardlessEMIPaymentMethod struct {
	CardlessEmi CardlessEMI `json:"cardless_emi"`
}

func (o *CardlessEMIPaymentMethod) GetCardlessEmi() CardlessEMI {
	if o == nil {
		return CardlessEMI{}
	}
	return o.CardlessEmi
}
