// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CardPaymentMethod - The card payment object is used to make payment using either plain card number, saved card instrument id or using cryptogram
type CardPaymentMethod struct {
	Card Card `json:"card"`
}

func (o *CardPaymentMethod) GetCard() Card {
	if o == nil {
		return Card{}
	}
	return o.Card
}
