// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CashbackDetailsCashbackType - Type of discount
type CashbackDetailsCashbackType string

const (
	CashbackDetailsCashbackTypeFlat       CashbackDetailsCashbackType = "flat"
	CashbackDetailsCashbackTypePercentage CashbackDetailsCashbackType = "percentage"
)

func (e CashbackDetailsCashbackType) ToPointer() *CashbackDetailsCashbackType {
	return &e
}

func (e *CashbackDetailsCashbackType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flat":
		fallthrough
	case "percentage":
		*e = CashbackDetailsCashbackType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CashbackDetailsCashbackType: %v", v)
	}
}

type CashbackDetails struct {
	// Type of discount
	CashbackType *CashbackDetailsCashbackType `json:"cashback_type,omitempty"`
	// Value of Discount.
	CashbackValue *string `json:"cashback_value,omitempty"`
	// Maximum Value of Cashback allowed.
	MaxCashbackAmount string `json:"max_cashback_amount"`
}

func (o *CashbackDetails) GetCashbackType() *CashbackDetailsCashbackType {
	if o == nil {
		return nil
	}
	return o.CashbackType
}

func (o *CashbackDetails) GetCashbackValue() *string {
	if o == nil {
		return nil
	}
	return o.CashbackValue
}

func (o *CashbackDetails) GetMaxCashbackAmount() string {
	if o == nil {
		return ""
	}
	return o.MaxCashbackAmount
}
