// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateTerminalRequest struct {
	// merchant’s internal terminal id
	TerminalID *string `json:"terminal_id,omitempty"`
	// terminal name to be assigned by merchants
	TerminalName string `json:"terminal_name"`
	// phone number assigned to the terminal
	TerminalPhoneNo string `json:"terminal_phone_no"`
}

func (o *CreateTerminalRequest) GetTerminalID() *string {
	if o == nil {
		return nil
	}
	return o.TerminalID
}

func (o *CreateTerminalRequest) GetTerminalName() string {
	if o == nil {
		return ""
	}
	return o.TerminalName
}

func (o *CreateTerminalRequest) GetTerminalPhoneNo() string {
	if o == nil {
		return ""
	}
	return o.TerminalPhoneNo
}
