// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CustomerDetailsCardlessEMI - Details of the customer for whom eligibility is being checked.
type CustomerDetailsCardlessEMI struct {
	// Phone Number of the customer
	CustomerPhone string `json:"customer_phone"`
}

func (o *CustomerDetailsCardlessEMI) GetCustomerPhone() string {
	if o == nil {
		return ""
	}
	return o.CustomerPhone
}
