// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// DiscountType - Type of discount
type DiscountType string

const (
	DiscountTypeFlat       DiscountType = "flat"
	DiscountTypePercentage DiscountType = "percentage"
)

func (e DiscountType) ToPointer() *DiscountType {
	return &e
}

func (e *DiscountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flat":
		fallthrough
	case "percentage":
		*e = DiscountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DiscountType: %v", v)
	}
}

type DiscountDetails struct {
	// Type of discount
	DiscountType DiscountType `json:"discount_type"`
	// Value of Discount.
	DiscountValue string `json:"discount_value"`
	// Maximum Value of Discount allowed.
	MaxDiscountAmount string `json:"max_discount_amount"`
}

func (o *DiscountDetails) GetDiscountType() DiscountType {
	if o == nil {
		return DiscountType("")
	}
	return o.DiscountType
}

func (o *DiscountDetails) GetDiscountValue() string {
	if o == nil {
		return ""
	}
	return o.DiscountValue
}

func (o *DiscountDetails) GetMaxDiscountAmount() string {
	if o == nil {
		return ""
	}
	return o.MaxDiscountAmount
}
