// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EligibleCardlessEMIEntity struct {
	Eligibility   *string            `json:"eligibility,omitempty"`
	EntityDetails *CardlessEMIEntity `json:"entity_details,omitempty"`
	EntityType    *string            `json:"entity_type,omitempty"`
	EntityValue   *string            `json:"entity_value,omitempty"`
}

func (o *EligibleCardlessEMIEntity) GetEligibility() *string {
	if o == nil {
		return nil
	}
	return o.Eligibility
}

func (o *EligibleCardlessEMIEntity) GetEntityDetails() *CardlessEMIEntity {
	if o == nil {
		return nil
	}
	return o.EntityDetails
}

func (o *EligibleCardlessEMIEntity) GetEntityType() *string {
	if o == nil {
		return nil
	}
	return o.EntityType
}

func (o *EligibleCardlessEMIEntity) GetEntityValue() *string {
	if o == nil {
		return nil
	}
	return o.EntityValue
}
