// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EligiblePaylater struct {
	Eligibility   *string         `json:"eligibility,omitempty"`
	EntityDetails *PaylaterEntity `json:"entity_details,omitempty"`
	EntityType    *string         `json:"entity_type,omitempty"`
	EntityValue   *string         `json:"entity_value,omitempty"`
}

func (o *EligiblePaylater) GetEligibility() *string {
	if o == nil {
		return nil
	}
	return o.Eligibility
}

func (o *EligiblePaylater) GetEntityDetails() *PaylaterEntity {
	if o == nil {
		return nil
	}
	return o.EntityDetails
}

func (o *EligiblePaylater) GetEntityType() *string {
	if o == nil {
		return nil
	}
	return o.EntityType
}

func (o *EligiblePaylater) GetEntityValue() *string {
	if o == nil {
		return nil
	}
	return o.EntityValue
}
