// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EMIOffer struct {
	// Bank Name
	BankName string  `json:"bank_name"`
	Tenures  []int64 `json:"tenures,omitempty"`
	// Type of emi offer. Possible values are `credit_card_emi`, `debit_card_emi`, `cardless_emi`
	Type string `json:"type"`
}

func (o *EMIOffer) GetBankName() string {
	if o == nil {
		return ""
	}
	return o.BankName
}

func (o *EMIOffer) GetTenures() []int64 {
	if o == nil {
		return nil
	}
	return o.Tenures
}

func (o *EMIOffer) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
