// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EMIPlansArray struct {
	Currency      *string `json:"currency,omitempty"`
	Emi           *int64  `json:"emi,omitempty"`
	InterestRate  *int64  `json:"interest_rate,omitempty"`
	Tenure        *int64  `json:"tenure,omitempty"`
	TotalAmount   *int64  `json:"total_amount,omitempty"`
	TotalInterest *int64  `json:"total_interest,omitempty"`
}

func (o *EMIPlansArray) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *EMIPlansArray) GetEmi() *int64 {
	if o == nil {
		return nil
	}
	return o.Emi
}

func (o *EMIPlansArray) GetInterestRate() *int64 {
	if o == nil {
		return nil
	}
	return o.InterestRate
}

func (o *EMIPlansArray) GetTenure() *int64 {
	if o == nil {
		return nil
	}
	return o.Tenure
}

func (o *EMIPlansArray) GetTotalAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalAmount
}

func (o *EMIPlansArray) GetTotalInterest() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalInterest
}
