// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FetchSettlementReconRequestFilters - Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
type FetchSettlementReconRequestFilters struct {
	// List of settlement IDs for which you want the settlement reconciliation details.
	CfSettlementIds []int64 `json:"cf_settlement_ids,omitempty"`
	// Specify the end date till when you want the settlement reconciliation details.
	EndDate *string `json:"end_date,omitempty"`
	// List of settlement UTRs for which you want the settlement reconciliation details.
	SettlementUtrs []string `json:"settlement_utrs,omitempty"`
	// Specify the start date from when you want the settlement reconciliation details.
	StartDate *string `json:"start_date,omitempty"`
}

func (o *FetchSettlementReconRequestFilters) GetCfSettlementIds() []int64 {
	if o == nil {
		return nil
	}
	return o.CfSettlementIds
}

func (o *FetchSettlementReconRequestFilters) GetEndDate() *string {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *FetchSettlementReconRequestFilters) GetSettlementUtrs() []string {
	if o == nil {
		return nil
	}
	return o.SettlementUtrs
}

func (o *FetchSettlementReconRequestFilters) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}

// FetchSettlementReconRequestPagination - To fetch the next set of settlements, pass the cursor received in the response to the next API call.
//
//	To receive the data for the first time, pass the cursor as null.
//	Limit would be number of settlements that you want to receive.
type FetchSettlementReconRequestPagination struct {
	// Specifies from where the next set of settlement details should be fetched.
	Cursor *string `json:"cursor,omitempty"`
	// The number of settlements you want to fetch. Maximum limit is 1000, default value is 10.
	Limit int64 `json:"limit"`
}

func (o *FetchSettlementReconRequestPagination) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *FetchSettlementReconRequestPagination) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

type FetchSettlementReconRequest struct {
	// Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
	Filters FetchSettlementReconRequestFilters `json:"filters"`
	// To fetch the next set of settlements, pass the cursor received in the response to the next API call.
	//  To receive the data for the first time, pass the cursor as null.
	//  Limit would be number of settlements that you want to receive.
	Pagination FetchSettlementReconRequestPagination `json:"pagination"`
}

func (o *FetchSettlementReconRequest) GetFilters() FetchSettlementReconRequestFilters {
	if o == nil {
		return FetchSettlementReconRequestFilters{}
	}
	return o.Filters
}

func (o *FetchSettlementReconRequest) GetPagination() FetchSettlementReconRequestPagination {
	if o == nil {
		return FetchSettlementReconRequestPagination{}
	}
	return o.Pagination
}
