// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FetchSettlementReconData struct {
	// Other adjustment remarks.
	AdjustmentRemarks *string `json:"adjustment_remarks,omitempty"`
	// Cashfree Payments unique ID to identify a payment.
	CfPaymentID *int64 `json:"cf_payment_id,omitempty"`
	// Unique ID to identify the settlement.
	CfSettlementID *int64 `json:"cf_settlement_id,omitempty"`
	// Specifies whether the dispute was closed in favor of the merchant or customer. Possible values - Merchant, Customer.
	ClosedInFavorOf *string `json:"closed_in_favor_of,omitempty"`
	// Customer email.
	CustomerEmail *string `json:"customer_email,omitempty"`
	// Customer name.
	CustomerName *string `json:"customer_name,omitempty"`
	// Customer phone number.
	CustomerPhone *string `json:"customer_phone,omitempty"`
	// Category of the dispute - Dispute code and the reason for dispute is shown.
	DisputeCategory *string `json:"dispute_category,omitempty"`
	// Note regarding the dispute.
	DisputeNote *string `json:"dispute_note,omitempty"`
	// Date and time when the dispute was resolved.
	DisputeResolvedOn *string `json:"dispute_resolved_on,omitempty"`
	// Recon
	Entity *string `json:"entity,omitempty"`
	// Amount corresponding to the event. Example, refund amount, dispute amount, payment amount, etc.
	EventAmount *float64 `json:"event_amount,omitempty"`
	// Curreny type - INR.
	EventCurrency *string `json:"event_currency,omitempty"`
	// Unique ID associated with the event.
	EventID *string `json:"event_id,omitempty"`
	// Amount that is part of the settlement corresponding to the event.
	EventSettlementAmount *float64 `json:"event_settlement_amount,omitempty"`
	// Status of the event. Example - SUCCESS, FAILED, PENDING, CANCELLED.
	EventStatus *string `json:"event_status,omitempty"`
	// Time associated with the event. Example, transaction time, dispute initiation time
	EventTime *string `json:"event_time,omitempty"`
	// The event type can be PAYMENT, REFUND, REFUND_REVERSAL, DISPUTE, DISPUTE_REVERSAL, CHARGEBACK, CHARGEBACK_REVERSAL, OTHER_ADJUSTMENT.
	EventType *string `json:"event_type,omitempty"`
	// The amount which was passed at the order creation time.
	OrderAmount *float64 `json:"order_amount,omitempty"`
	// Unique order ID. Alphanumeric and only '-' and '_' allowed.
	OrderID *string `json:"order_id,omitempty"`
	// Payment amount captured.
	PaymentAmount *float64 `json:"payment_amount,omitempty"`
	// Service charge applicable for the payment.
	PaymentServiceCharge *float64 `json:"payment_service_charge,omitempty"`
	// Service tax applicable on the payment.
	PaymentServiceTax *float64 `json:"payment_service_tax,omitempty"`
	// Date and time when the payment was initiated.
	PaymentTime *string `json:"payment_time,omitempty"`
	// Unique transaction reference number of the payment.
	PaymentUtr *string `json:"payment_utr,omitempty"`
	// The bank reference number for refund.
	RefundArn *string `json:"refund_arn,omitempty"`
	// An unique ID associated with the refund.
	RefundID *string `json:"refund_id,omitempty"`
	// A refund note for your reference.
	RefundNote *string `json:"refund_note,omitempty"`
	// Date and time when the refund was processed.
	RefundProcessedAt *string `json:"refund_processed_at,omitempty"`
	// Indicates if it is CREDIT/DEBIT sale.
	SaleType *string `json:"sale_type,omitempty"`
	// Date and time when the settlement was processed.
	SettlementDate *string `json:"settlement_date,omitempty"`
	// Unique transaction reference number of the settlement.
	SettlementUtr *string `json:"settlement_utr,omitempty"`
	// Service charge that is applicable for splitting the payment.
	SplitServiceCharge *float64 `json:"split_service_charge,omitempty"`
	// Service tax applicable for splitting the amount to vendors.
	SplitServiceTax *float64 `json:"split_service_tax,omitempty"`
	// Vendor commission applicable for this transaction.
	VendorCommission *float64 `json:"vendor_commission,omitempty"`
}

func (o *FetchSettlementReconData) GetAdjustmentRemarks() *string {
	if o == nil {
		return nil
	}
	return o.AdjustmentRemarks
}

func (o *FetchSettlementReconData) GetCfPaymentID() *int64 {
	if o == nil {
		return nil
	}
	return o.CfPaymentID
}

func (o *FetchSettlementReconData) GetCfSettlementID() *int64 {
	if o == nil {
		return nil
	}
	return o.CfSettlementID
}

func (o *FetchSettlementReconData) GetClosedInFavorOf() *string {
	if o == nil {
		return nil
	}
	return o.ClosedInFavorOf
}

func (o *FetchSettlementReconData) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *FetchSettlementReconData) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *FetchSettlementReconData) GetCustomerPhone() *string {
	if o == nil {
		return nil
	}
	return o.CustomerPhone
}

func (o *FetchSettlementReconData) GetDisputeCategory() *string {
	if o == nil {
		return nil
	}
	return o.DisputeCategory
}

func (o *FetchSettlementReconData) GetDisputeNote() *string {
	if o == nil {
		return nil
	}
	return o.DisputeNote
}

func (o *FetchSettlementReconData) GetDisputeResolvedOn() *string {
	if o == nil {
		return nil
	}
	return o.DisputeResolvedOn
}

func (o *FetchSettlementReconData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *FetchSettlementReconData) GetEventAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.EventAmount
}

func (o *FetchSettlementReconData) GetEventCurrency() *string {
	if o == nil {
		return nil
	}
	return o.EventCurrency
}

func (o *FetchSettlementReconData) GetEventID() *string {
	if o == nil {
		return nil
	}
	return o.EventID
}

func (o *FetchSettlementReconData) GetEventSettlementAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.EventSettlementAmount
}

func (o *FetchSettlementReconData) GetEventStatus() *string {
	if o == nil {
		return nil
	}
	return o.EventStatus
}

func (o *FetchSettlementReconData) GetEventTime() *string {
	if o == nil {
		return nil
	}
	return o.EventTime
}

func (o *FetchSettlementReconData) GetEventType() *string {
	if o == nil {
		return nil
	}
	return o.EventType
}

func (o *FetchSettlementReconData) GetOrderAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderAmount
}

func (o *FetchSettlementReconData) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *FetchSettlementReconData) GetPaymentAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.PaymentAmount
}

func (o *FetchSettlementReconData) GetPaymentServiceCharge() *float64 {
	if o == nil {
		return nil
	}
	return o.PaymentServiceCharge
}

func (o *FetchSettlementReconData) GetPaymentServiceTax() *float64 {
	if o == nil {
		return nil
	}
	return o.PaymentServiceTax
}

func (o *FetchSettlementReconData) GetPaymentTime() *string {
	if o == nil {
		return nil
	}
	return o.PaymentTime
}

func (o *FetchSettlementReconData) GetPaymentUtr() *string {
	if o == nil {
		return nil
	}
	return o.PaymentUtr
}

func (o *FetchSettlementReconData) GetRefundArn() *string {
	if o == nil {
		return nil
	}
	return o.RefundArn
}

func (o *FetchSettlementReconData) GetRefundID() *string {
	if o == nil {
		return nil
	}
	return o.RefundID
}

func (o *FetchSettlementReconData) GetRefundNote() *string {
	if o == nil {
		return nil
	}
	return o.RefundNote
}

func (o *FetchSettlementReconData) GetRefundProcessedAt() *string {
	if o == nil {
		return nil
	}
	return o.RefundProcessedAt
}

func (o *FetchSettlementReconData) GetSaleType() *string {
	if o == nil {
		return nil
	}
	return o.SaleType
}

func (o *FetchSettlementReconData) GetSettlementDate() *string {
	if o == nil {
		return nil
	}
	return o.SettlementDate
}

func (o *FetchSettlementReconData) GetSettlementUtr() *string {
	if o == nil {
		return nil
	}
	return o.SettlementUtr
}

func (o *FetchSettlementReconData) GetSplitServiceCharge() *float64 {
	if o == nil {
		return nil
	}
	return o.SplitServiceCharge
}

func (o *FetchSettlementReconData) GetSplitServiceTax() *float64 {
	if o == nil {
		return nil
	}
	return o.SplitServiceTax
}

func (o *FetchSettlementReconData) GetVendorCommission() *float64 {
	if o == nil {
		return nil
	}
	return o.VendorCommission
}

type FetchSettlementRecon struct {
	// Specifies from where the next set of settlement details should be fetched.
	Cursor *string                    `json:"cursor,omitempty"`
	Data   []FetchSettlementReconData `json:"data,omitempty"`
	// Number of settlements you want to fetch in the next iteration.
	Limit *int64 `json:"limit,omitempty"`
}

func (o *FetchSettlementRecon) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *FetchSettlementRecon) GetData() []FetchSettlementReconData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *FetchSettlementRecon) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}
