// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkNotifyEntity struct {
	// If "true", Cashfree will send email on customer_email
	SendEmail *bool `json:"send_email,omitempty"`
	// If "true", Cashfree will send sms on customer_phone
	SendSms *bool `json:"send_sms,omitempty"`
}

func (o *LinkNotifyEntity) GetSendEmail() *bool {
	if o == nil {
		return nil
	}
	return o.SendEmail
}

func (o *LinkNotifyEntity) GetSendSms() *bool {
	if o == nil {
		return nil
	}
	return o.SendSms
}
