// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkCustomerDetailsEntity struct {
	// Customer email address
	CustomerEmail *string `json:"customer_email,omitempty"`
	// Customer name
	CustomerName *string `json:"customer_name,omitempty"`
	// Customer phone number
	CustomerPhone string `json:"customer_phone"`
}

func (o *LinkCustomerDetailsEntity) GetCustomerEmail() *string {
	if o == nil {
		return nil
	}
	return o.CustomerEmail
}

func (o *LinkCustomerDetailsEntity) GetCustomerName() *string {
	if o == nil {
		return nil
	}
	return o.CustomerName
}

func (o *LinkCustomerDetailsEntity) GetCustomerPhone() string {
	if o == nil {
		return ""
	}
	return o.CustomerPhone
}
