// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkMetaEntity struct {
	// Notification URL for server-server communication. It should be an https URL.
	NotifyURL *string `json:"notify_url,omitempty"`
	// Allowed payment modes for this link. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc", "nb", "upi", "paypal", "app". Leave it blank to show all available payment methods
	PaymentMethods *string `json:"payment_methods,omitempty"`
	// The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250.
	ReturnURL *string `json:"return_url,omitempty"`
	// If "true", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere
	UpiIntent *bool `json:"upi_intent,omitempty"`
}

func (o *LinkMetaEntity) GetNotifyURL() *string {
	if o == nil {
		return nil
	}
	return o.NotifyURL
}

func (o *LinkMetaEntity) GetPaymentMethods() *string {
	if o == nil {
		return nil
	}
	return o.PaymentMethods
}

func (o *LinkMetaEntity) GetReturnURL() *string {
	if o == nil {
		return nil
	}
	return o.ReturnURL
}

func (o *LinkMetaEntity) GetUpiIntent() *bool {
	if o == nil {
		return nil
	}
	return o.UpiIntent
}
