// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LinkCancelledError - Cannot cancel Payment Link if status is not ACTIVE
type LinkCancelledError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

func (o *LinkCancelledError) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *LinkCancelledError) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *LinkCancelledError) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
