// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkOrdersResponse struct {
	CfOrderID       *int64                     `json:"cf_order_id,omitempty"`
	CustomerDetails *LinkCustomerDetailsEntity `json:"customer_details,omitempty"`
	Entity          *string                    `json:"entity,omitempty"`
	OrderAmount     *float64                   `json:"order_amount,omitempty"`
	OrderCurrency   *string                    `json:"order_currency,omitempty"`
	OrderExpiryTime *string                    `json:"order_expiry_time,omitempty"`
	OrderID         *string                    `json:"order_id,omitempty"`
	OrderNote       *string                    `json:"order_note,omitempty"`
	OrderStatus     *string                    `json:"order_status,omitempty"`
	OrderToken      *string                    `json:"order_token,omitempty"`
	Payments        *PaymentURLObject          `json:"payments,omitempty"`
	Refunds         *RefundURLObject           `json:"refunds,omitempty"`
	Settlements     *SettlementURLObject       `json:"settlements,omitempty"`
}

func (o *LinkOrdersResponse) GetCfOrderID() *int64 {
	if o == nil {
		return nil
	}
	return o.CfOrderID
}

func (o *LinkOrdersResponse) GetCustomerDetails() *LinkCustomerDetailsEntity {
	if o == nil {
		return nil
	}
	return o.CustomerDetails
}

func (o *LinkOrdersResponse) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *LinkOrdersResponse) GetOrderAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderAmount
}

func (o *LinkOrdersResponse) GetOrderCurrency() *string {
	if o == nil {
		return nil
	}
	return o.OrderCurrency
}

func (o *LinkOrdersResponse) GetOrderExpiryTime() *string {
	if o == nil {
		return nil
	}
	return o.OrderExpiryTime
}

func (o *LinkOrdersResponse) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *LinkOrdersResponse) GetOrderNote() *string {
	if o == nil {
		return nil
	}
	return o.OrderNote
}

func (o *LinkOrdersResponse) GetOrderStatus() *string {
	if o == nil {
		return nil
	}
	return o.OrderStatus
}

func (o *LinkOrdersResponse) GetOrderToken() *string {
	if o == nil {
		return nil
	}
	return o.OrderToken
}

func (o *LinkOrdersResponse) GetPayments() *PaymentURLObject {
	if o == nil {
		return nil
	}
	return o.Payments
}

func (o *LinkOrdersResponse) GetRefunds() *RefundURLObject {
	if o == nil {
		return nil
	}
	return o.Refunds
}

func (o *LinkOrdersResponse) GetSettlements() *SettlementURLObject {
	if o == nil {
		return nil
	}
	return o.Settlements
}
