// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NBOffer struct {
	BankName string `json:"bank_name"`
}

func (o *NBOffer) GetBankName() string {
	if o == nil {
		return ""
	}
	return o.BankName
}
