// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Netbanking struct {
	// The channel for netbanking will always be `link`
	Channel string `json:"channel"`
	// Bank code
	NetbankingBankCode int `json:"netbanking_bank_code"`
}

func (o *Netbanking) GetChannel() string {
	if o == nil {
		return ""
	}
	return o.Channel
}

func (o *Netbanking) GetNetbankingBankCode() int {
	if o == nil {
		return 0
	}
	return o.NetbankingBankCode
}
