// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NetBankingPaymentMethod struct {
	Netbanking Netbanking `json:"netbanking"`
}

func (o *NetBankingPaymentMethod) GetNetbanking() Netbanking {
	if o == nil {
		return Netbanking{}
	}
	return o.Netbanking
}
