// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferCard struct {
	Card CardOffer `json:"card"`
}

func (o *OfferCard) GetCard() CardOffer {
	if o == nil {
		return CardOffer{}
	}
	return o.Card
}
