// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferFilters struct {
	// Array of offer_type to be filtered.
	OfferType []OfferType `json:"offer_type,omitempty"`
}

func (o *OfferFilters) GetOfferType() []OfferType {
	if o == nil {
		return nil
	}
	return o.OfferType
}
