// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferPaylater struct {
	Paylater PaylaterOffer `json:"paylater"`
}

func (o *OfferPaylater) GetPaylater() PaylaterOffer {
	if o == nil {
		return PaylaterOffer{}
	}
	return o.Paylater
}
