// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferMeta struct {
	// Unique identifier for the Offer.
	OfferCode string `json:"offer_code"`
	// Description for the Offer.
	OfferDescription string `json:"offer_description"`
	// Expiry Time for the Offer
	OfferEndTime string `json:"offer_end_time"`
	// Start Time for the Offer
	OfferStartTime string `json:"offer_start_time"`
	// Title for the Offer.
	OfferTitle string `json:"offer_title"`
}

func (o *OfferMeta) GetOfferCode() string {
	if o == nil {
		return ""
	}
	return o.OfferCode
}

func (o *OfferMeta) GetOfferDescription() string {
	if o == nil {
		return ""
	}
	return o.OfferDescription
}

func (o *OfferMeta) GetOfferEndTime() string {
	if o == nil {
		return ""
	}
	return o.OfferEndTime
}

func (o *OfferMeta) GetOfferStartTime() string {
	if o == nil {
		return ""
	}
	return o.OfferStartTime
}

func (o *OfferMeta) GetOfferTitle() string {
	if o == nil {
		return ""
	}
	return o.OfferTitle
}
