// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OfferTncOfferTncType - TnC Type for the Offer. It can be either `text` or `link`
type OfferTncOfferTncType string

const (
	OfferTncOfferTncTypeLink OfferTncOfferTncType = "link"
	OfferTncOfferTncTypePost OfferTncOfferTncType = "post"
)

func (e OfferTncOfferTncType) ToPointer() *OfferTncOfferTncType {
	return &e
}

func (e *OfferTncOfferTncType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link":
		fallthrough
	case "post":
		*e = OfferTncOfferTncType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OfferTncOfferTncType: %v", v)
	}
}

type OfferTnc struct {
	// TnC Type for the Offer. It can be either `text` or `link`
	OfferTncType OfferTncOfferTncType `json:"offer_tnc_type"`
	// TnC for the Offer.
	OfferTncValue string `json:"offer_tnc_value"`
}

func (o *OfferTnc) GetOfferTncType() OfferTncOfferTncType {
	if o == nil {
		return OfferTncOfferTncType("")
	}
	return o.OfferTncType
}

func (o *OfferTnc) GetOfferTncValue() string {
	if o == nil {
		return ""
	}
	return o.OfferTncValue
}
