// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferWallet struct {
	App *WalletOffer `json:"app,omitempty"`
}

func (o *OfferWallet) GetApp() *WalletOffer {
	if o == nil {
		return nil
	}
	return o.App
}
