// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OfferType string

const (
	OfferTypeDiscount            OfferType = "DISCOUNT"
	OfferTypeCashback            OfferType = "CASHBACK"
	OfferTypeDiscountAndCashback OfferType = "DISCOUNT_AND_CASHBACK"
	OfferTypeNoCostEmi           OfferType = "NO_COST_EMI"
)

func (e OfferType) ToPointer() *OfferType {
	return &e
}

func (e *OfferType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DISCOUNT":
		fallthrough
	case "CASHBACK":
		fallthrough
	case "DISCOUNT_AND_CASHBACK":
		fallthrough
	case "NO_COST_EMI":
		*e = OfferType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OfferType: %v", v)
	}
}
