// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferNB struct {
	Netbanking *NBOffer `json:"netbanking,omitempty"`
}

func (o *OfferNB) GetNetbanking() *NBOffer {
	if o == nil {
		return nil
	}
	return o.Netbanking
}
