// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OfferTncType - TnC Type for the Offer. It can be either `text` or `link`
type OfferTncType string

const (
	OfferTncTypeLink OfferTncType = "link"
	OfferTncTypePost OfferTncType = "post"
)

func (e OfferTncType) ToPointer() *OfferTncType {
	return &e
}

func (e *OfferTncType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link":
		fallthrough
	case "post":
		*e = OfferTncType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OfferTncType: %v", v)
	}
}

type OfferTnc struct {
	// TnC Type for the Offer. It can be either `text` or `link`
	OfferTncType OfferTncType `json:"offer_tnc_type"`
	// TnC for the Offer.
	OfferTncValue string `json:"offer_tnc_value"`
}

func (o *OfferTnc) GetOfferTncType() OfferTncType {
	if o == nil {
		return OfferTncType("")
	}
	return o.OfferTncType
}

func (o *OfferTnc) GetOfferTncValue() string {
	if o == nil {
		return ""
	}
	return o.OfferTncValue
}
