// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferEMI struct {
	Emi EMIOffer `json:"emi"`
}

func (o *OfferEMI) GetEmi() EMIOffer {
	if o == nil {
		return EMIOffer{}
	}
	return o.Emi
}
