// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferQueries struct {
	// Amount of the order. OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
	Amount *float64 `json:"amount,omitempty"`
	// OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
	OrderID *string `json:"order_id,omitempty"`
}

func (o *OfferQueries) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *OfferQueries) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}
