// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferUPI struct {
	Upi UPIOffer `json:"upi"`
}

func (o *OfferUPI) GetUpi() UPIOffer {
	if o == nil {
		return UPIOffer{}
	}
	return o.Upi
}
