// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OTPRequestAction - The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
type OTPRequestAction string

const (
	OTPRequestActionSubmitOtp OTPRequestAction = "SUBMIT_OTP"
	OTPRequestActionResendOtp OTPRequestAction = "RESEND_OTP"
)

func (e OTPRequestAction) ToPointer() *OTPRequestAction {
	return &e
}

func (e *OTPRequestAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SUBMIT_OTP":
		fallthrough
	case "RESEND_OTP":
		*e = OTPRequestAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OTPRequestAction: %v", v)
	}
}

type OTPRequest struct {
	// The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
	Action OTPRequestAction `json:"action"`
	// OTP to be submitted
	Otp string `json:"otp"`
}

func (o *OTPRequest) GetAction() OTPRequestAction {
	if o == nil {
		return OTPRequestAction("")
	}
	return o.Action
}

func (o *OTPRequest) GetOtp() string {
	if o == nil {
		return ""
	}
	return o.Otp
}
