// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaylaterPaymentMethod struct {
	Paylater Paylater `json:"paylater"`
}

func (o *PaylaterPaymentMethod) GetPaylater() Paylater {
	if o == nil {
		return Paylater{}
	}
	return o.Paylater
}
