// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentMethodUPIInPaymentsEntity struct {
	Channel string  `json:"channel"`
	UpiID   *string `json:"upi_id,omitempty"`
}

func (o *PaymentMethodUPIInPaymentsEntity) GetChannel() string {
	if o == nil {
		return ""
	}
	return o.Channel
}

func (o *PaymentMethodUPIInPaymentsEntity) GetUpiID() *string {
	if o == nil {
		return nil
	}
	return o.UpiID
}
