// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type PaymentMethodInPaymentsEntityPaymentMethodType string

const (
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardInPaymentsEntity        PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodCardInPaymentsEntity"
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodNetBankingInPaymentsEntity  PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodNetBankingInPaymentsEntity"
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodUPIInPaymentsEntity         PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodUPIInPaymentsEntity"
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodAppInPaymentsEntity         PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodAppInPaymentsEntity"
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardlessEMIInPaymentsEntity PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodCardlessEMIInPaymentsEntity"
	PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodPaylaterInPaymentsEntity    PaymentMethodInPaymentsEntityPaymentMethodType = "PaymentMethodPaylaterInPaymentsEntity"
)

type PaymentMethodInPaymentsEntityPaymentMethod struct {
	PaymentMethodCardInPaymentsEntity        *PaymentMethodCardInPaymentsEntity
	PaymentMethodNetBankingInPaymentsEntity  *PaymentMethodNetBankingInPaymentsEntity
	PaymentMethodUPIInPaymentsEntity         *PaymentMethodUPIInPaymentsEntity
	PaymentMethodAppInPaymentsEntity         *PaymentMethodAppInPaymentsEntity
	PaymentMethodCardlessEMIInPaymentsEntity *PaymentMethodCardlessEMIInPaymentsEntity
	PaymentMethodPaylaterInPaymentsEntity    *PaymentMethodPaylaterInPaymentsEntity

	Type PaymentMethodInPaymentsEntityPaymentMethodType
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodCardInPaymentsEntity(paymentMethodCardInPaymentsEntity PaymentMethodCardInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodCardInPaymentsEntity: &paymentMethodCardInPaymentsEntity,
		Type:                              typ,
	}
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodNetBankingInPaymentsEntity(paymentMethodNetBankingInPaymentsEntity PaymentMethodNetBankingInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodNetBankingInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodNetBankingInPaymentsEntity: &paymentMethodNetBankingInPaymentsEntity,
		Type:                                    typ,
	}
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodUPIInPaymentsEntity(paymentMethodUPIInPaymentsEntity PaymentMethodUPIInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodUPIInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodUPIInPaymentsEntity: &paymentMethodUPIInPaymentsEntity,
		Type:                             typ,
	}
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodAppInPaymentsEntity(paymentMethodAppInPaymentsEntity PaymentMethodAppInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodAppInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodAppInPaymentsEntity: &paymentMethodAppInPaymentsEntity,
		Type:                             typ,
	}
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodCardlessEMIInPaymentsEntity(paymentMethodCardlessEMIInPaymentsEntity PaymentMethodCardlessEMIInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardlessEMIInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodCardlessEMIInPaymentsEntity: &paymentMethodCardlessEMIInPaymentsEntity,
		Type:                                     typ,
	}
}

func CreatePaymentMethodInPaymentsEntityPaymentMethodPaymentMethodPaylaterInPaymentsEntity(paymentMethodPaylaterInPaymentsEntity PaymentMethodPaylaterInPaymentsEntity) PaymentMethodInPaymentsEntityPaymentMethod {
	typ := PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodPaylaterInPaymentsEntity

	return PaymentMethodInPaymentsEntityPaymentMethod{
		PaymentMethodPaylaterInPaymentsEntity: &paymentMethodPaylaterInPaymentsEntity,
		Type:                                  typ,
	}
}

func (u *PaymentMethodInPaymentsEntityPaymentMethod) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	paymentMethodUPIInPaymentsEntity := new(PaymentMethodUPIInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodUPIInPaymentsEntity); err == nil {
		u.PaymentMethodUPIInPaymentsEntity = paymentMethodUPIInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodUPIInPaymentsEntity
		return nil
	}

	paymentMethodNetBankingInPaymentsEntity := new(PaymentMethodNetBankingInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodNetBankingInPaymentsEntity); err == nil {
		u.PaymentMethodNetBankingInPaymentsEntity = paymentMethodNetBankingInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodNetBankingInPaymentsEntity
		return nil
	}

	paymentMethodAppInPaymentsEntity := new(PaymentMethodAppInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodAppInPaymentsEntity); err == nil {
		u.PaymentMethodAppInPaymentsEntity = paymentMethodAppInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodAppInPaymentsEntity
		return nil
	}

	paymentMethodCardlessEMIInPaymentsEntity := new(PaymentMethodCardlessEMIInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodCardlessEMIInPaymentsEntity); err == nil {
		u.PaymentMethodCardlessEMIInPaymentsEntity = paymentMethodCardlessEMIInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardlessEMIInPaymentsEntity
		return nil
	}

	paymentMethodPaylaterInPaymentsEntity := new(PaymentMethodPaylaterInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodPaylaterInPaymentsEntity); err == nil {
		u.PaymentMethodPaylaterInPaymentsEntity = paymentMethodPaylaterInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodPaylaterInPaymentsEntity
		return nil
	}

	paymentMethodCardInPaymentsEntity := new(PaymentMethodCardInPaymentsEntity)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodCardInPaymentsEntity); err == nil {
		u.PaymentMethodCardInPaymentsEntity = paymentMethodCardInPaymentsEntity
		u.Type = PaymentMethodInPaymentsEntityPaymentMethodTypePaymentMethodCardInPaymentsEntity
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u PaymentMethodInPaymentsEntityPaymentMethod) MarshalJSON() ([]byte, error) {
	if u.PaymentMethodUPIInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodUPIInPaymentsEntity)
	}

	if u.PaymentMethodNetBankingInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodNetBankingInPaymentsEntity)
	}

	if u.PaymentMethodAppInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodAppInPaymentsEntity)
	}

	if u.PaymentMethodCardlessEMIInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodCardlessEMIInPaymentsEntity)
	}

	if u.PaymentMethodPaylaterInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodPaylaterInPaymentsEntity)
	}

	if u.PaymentMethodCardInPaymentsEntity != nil {
		return json.Marshal(u.PaymentMethodCardInPaymentsEntity)
	}

	return nil, errors.New("could not marshal union type: all fields are null")

}

type PaymentMethodInPaymentsEntity struct {
	PaymentMethod *PaymentMethodInPaymentsEntityPaymentMethod `json:"payment_method,omitempty"`
}

func (o *PaymentMethodInPaymentsEntity) GetPaymentMethod() *PaymentMethodInPaymentsEntityPaymentMethod {
	if o == nil {
		return nil
	}
	return o.PaymentMethod
}
