// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentMethodNetBankingInPaymentsEntity struct {
	Channel            string `json:"channel"`
	NetbankingBankCode string `json:"netbanking_bank_code"`
	NetbankingBankName string `json:"netbanking_bank_name"`
}

func (o *PaymentMethodNetBankingInPaymentsEntity) GetChannel() string {
	if o == nil {
		return ""
	}
	return o.Channel
}

func (o *PaymentMethodNetBankingInPaymentsEntity) GetNetbankingBankCode() string {
	if o == nil {
		return ""
	}
	return o.NetbankingBankCode
}

func (o *PaymentMethodNetBankingInPaymentsEntity) GetNetbankingBankName() string {
	if o == nil {
		return ""
	}
	return o.NetbankingBankName
}
