// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/go-sdk-full/pkg/types"
	"github.com/speakeasy-sdks/go-sdk-full/pkg/utils"
)

type RateLimitError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// rate_limit_error
	type_ *string `const:"rate_limit_error" json:"type,omitempty"`
}

func (r RateLimitError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RateLimitError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RateLimitError) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *RateLimitError) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *RateLimitError) GetType() *string {
	return types.String("rate_limit_error")
}
