// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CardTokenDetails struct {
}

type SavedInstrumentMeta struct {
	// Issuing bank name of saved card
	CardBankName *string `json:"card_bank_name,omitempty"`
	// Issuing country of saved card
	CardCountry *string `json:"card_country,omitempty"`
	// card scheme/network of the saved card
	CardNetwork      *string           `json:"card_network,omitempty"`
	CardTokenDetails *CardTokenDetails `json:"card_token_details,omitempty"`
	// Type of saved card
	CardType *string `json:"card_type,omitempty"`
}

func (o *SavedInstrumentMeta) GetCardBankName() *string {
	if o == nil {
		return nil
	}
	return o.CardBankName
}

func (o *SavedInstrumentMeta) GetCardCountry() *string {
	if o == nil {
		return nil
	}
	return o.CardCountry
}

func (o *SavedInstrumentMeta) GetCardNetwork() *string {
	if o == nil {
		return nil
	}
	return o.CardNetwork
}

func (o *SavedInstrumentMeta) GetCardTokenDetails() *CardTokenDetails {
	if o == nil {
		return nil
	}
	return o.CardTokenDetails
}

func (o *SavedInstrumentMeta) GetCardType() *string {
	if o == nil {
		return nil
	}
	return o.CardType
}
