// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UPIAuthorizeDetails struct {
	// Time by which this authorization should be approved by the customer.
	ApproveBy *string `json:"approve_by,omitempty"`
	// This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time.
	EndTime *string `json:"end_time,omitempty"`
	// This is the time when the UPI one time mandate will start
	StartTime *string `json:"start_time,omitempty"`
}

func (o *UPIAuthorizeDetails) GetApproveBy() *string {
	if o == nil {
		return nil
	}
	return o.ApproveBy
}

func (o *UPIAuthorizeDetails) GetEndTime() *string {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *UPIAuthorizeDetails) GetStartTime() *string {
	if o == nil {
		return nil
	}
	return o.StartTime
}
