// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UPIPaymentMethod struct {
	Upi Upi `json:"upi"`
}

func (o *UPIPaymentMethod) GetUpi() Upi {
	if o == nil {
		return Upi{}
	}
	return o.Upi
}
